# https://medium.com/@nieldw/caching-maven-dependencies-in-a-docker-build-dca6ca7ad612
FROM maven:3.6.1-jdk-8 AS target
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /build/src/
RUN mvn package